### ISSUE TITLE
Schematic diagram for IR connection

### ISSUE THREAD

**Issue by iDoka** [godFather89/HAP.js#2]
Hello Andrei!
Thanks for sharing video http://www.youtube.com/watch?v=8ku1HAMl4tU with demonstration IR working.
I see IR LED (TX) and 3-pin IR receiver on the maket board.
I guess using some glue logic for connecting to the ESP8266 module.
Could you share some schematic diagram for that connection to ESP8266 module ?
Thanks a lot.
Dmitry

**Comment by andrei-tatar** [comment]
It's just the IR LED via a transistor connected to GPIO14 and the receiver (TSOP4838 or some other 3.3V compatible) output connected to GPIO13.
It's just 3 extra components (LED, IR rx and a transistor).

**Comment by iDoka** [comment]
Thanks Andrei!
One more question: the active control level is positive?
Like this schematic diagram: http://tech.cyborg5.com/files/2013/03/ir_out_1_trans_schematic.png

**Comment by andrei-tatar** [comment]
Yes, it's positive. A 0 means the LED is off and a 1 means the LED is on. You can see it in the code: https://github.com/andrei-tatar/HAP.js/blob/master/ESP8266/hap_ir/user/user_main.c
